version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sems
      POSTGRES_USER: sems_user
      POSTGRES_PASSWORD: sems_password
    volumes:
      - ./app/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=sems
      - POSTGRES_USER=sems_user
      - POSTGRES_PASSWORD=sems_password
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - API_KEY=replace-with-client-api-key
      - EMBEDDING_URL=${EMBEDDING_URL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_URL=${LLM_URL}
      - LLM_MODEL=${LLM_MODEL}
      - PROVIDER_API_KEY=${PROVIDER_API_KEY}
      - HOT_MAX_AGE_SECONDS=${HOT_MAX_AGE_SECONDS}
      - WARM_MAX_AGE_SECONDS=${WARM_MAX_AGE_SECONDS}
      - COMPRESSED_DIM=${COMPRESSED_DIM}
      - BINDER_SCORE_THRESHOLD=${BINDER_SCORE_THRESHOLD}
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
